<?php 
	echo View::jsTpl('header', 'item', 'form', 'msg');
?>

<div id="msgbox"></div>
<div id="header" class="w90 auto"></div>

<div class="row w90 auto">
	<div class="w25">
		<ul id="list" class="unstyled data"></ul>
	</div>
	 <div class="w60">
		<div id="show"></div>
	</div>
</div>
       



<?php echo Tag::js('jquery');?>
<?php echo Tag::js('underscore');?>
<?php echo Tag::js('backbone');?>
<?php echo Tag::js('main');?>
