<form id="data">
<label for="id">id</label>
<input type="text" placeholder="id" id="id" readonly value="<%=id%>"/> 
<label for="author">Autor</label>
<input type="text" placeholder="Autor" id="author" value="<%=author%>"/> 
<label for="title">Título</label>
<input type="text" placeholder="Titulo" id="title" value="<%=title%>"/>
<button class="save" type="button">Save</button>
<button class="delete" type="butoon">Delete</button>
</form>
