<!DOCTYPE html>
<html lang="es">
 <head>
	<meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
	<title>KumbiaPHP web &amp; App Framework &amp; BackBone.js</title>
	<link href="<?php echo PUBLIC_PATH ?>css/style.css" rel="stylesheet"/> 
	<link href="<?php echo PUBLIC_PATH ?>css/msg.css" rel="stylesheet"/> 

</head>
<body>
	<header>
	<h1>Administrador de Libros</h1>
	</header>
        <?php View::content(); ?>
	<footer>Copyrigth Alberto Berroteran 2012</footer>
</body>
</html>
