<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title>KumbiaPHP web &amp; App Framework &amp; BackBone.js</title>
  <?php Tag::css('style') ?>
  <?php echo Html::includeCss() ?>
</head>
<body>
	<div id='head'>
	<h1>Administrador de Libros</h1>
	</div>
        <?php View::content(); ?>
	<div id="foot">Copyrigth Alberto Berroteran 2012</div>
</body>
</html>
